language: node_js

node_js:
  - 6.0
  - stable

before_script:
  - "npm install"

script:
  - "npm test"

notifications:
  email:
    - cjrodr@yahoo.com

after_success:
    - './node_modules/.bin/nyc report --reporter=text-lcov | ./node_modules/.bin/coveralls'
